# Reference: https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/hyperparams/ppo.yml#L32
seed: 123

n_timesteps: !!float 1e6
policy: 'MlpPolicy'
n_steps: 512
batch_size: 256
gae_lambda: 0.95
gamma: 0.99
n_epochs: 20
ent_coef: 0.01
learning_rate: !!float 2e-4
clip_range: !!float 0.2
policy_kwargs: "dict(
                  activation_fn=nn.ELU,
                  net_arch=[64,64],
                  squash_output=False,
                )"
vf_coef: 1.0
max_grad_norm: 1.0
device: "cuda:0"


# SB3 Ant Hyperparams
# n_timesteps: !!float 1e7
# policy: 'MlpPolicy'
# n_steps: 512
# batch_size: 128 # num_envs*n_steps / num_minibatches
# gamma: 0.99
# gae_lambda: 0.9
# n_epochs: 20
# ent_coef: 0.0
# sde_sample_freq: 4
# max_grad_norm: 0.5
# vf_coef: 0.5
# learning_rate: !!float 3e-5
# use_sde: True
# clip_range: 0.4
# device: "cuda:0"
# policy_kwargs: "dict(
#                   log_std_init=-1,
#                   ortho_init=False,
#                   activation_fn=nn.ReLU,
#                   net_arch=dict(pi=[256, 256], vf=[256, 256])
#                 )"


# policy: 'MlpPolicy'
# n_timesteps: !!float 5e7
# batch_size: 256
# n_steps: 512
# gamma: 0.99
# learning_rate: !!float 2.5e-4
# ent_coef: 0.0
# clip_range: 0.2
# n_epochs: 10
# gae_lambda: 0.95
# max_grad_norm: 1.0
# vf_coef: 0.5
# device: "cuda:0"
# policy_kwargs: "dict(
#                   log_std_init=-1,
#                   ortho_init=False,
#                   activation_fn=nn.ReLU,
#                   net_arch=dict(pi=[256, 256], vf=[256, 256])
#                 )"
