seed: 1024
models:
  separate: false
  policy:
    class: GaussianMixin
    clip_actions: false
    clip_log_std: true
    min_log_std: -20.0
    max_log_std: 2.0
    initial_log_std: 0.0
    network:
    - name: net
      input: STATES
      layers:
      - 64
      - 64
      activations: elu
    output: ACTIONS
  value:
    class: DeterministicMixin
    clip_actions: false
    network:
    - name: net
      input: STATES
      layers:
      - 64
      - 64
      activations: elu
    output: ONE
memory:
  class: RandomMemory
  memory_size: -1
agent:
  class: PPO
  rollouts: 64
  learning_epochs: 8
  mini_batches: 8
  discount_factor: 0.99
  lambda: 0.95
  learning_rate: 0.0002
  learning_rate_scheduler: KLAdaptiveLR
  learning_rate_scheduler_kwargs:
    kl_threshold: 0.008
  state_preprocessor: null
  state_preprocessor_kwargs: null
  value_preprocessor: null
  value_preprocessor_kwargs: null
  random_timesteps: 0
  learning_starts: 0
  grad_norm_clip: 1.0
  ratio_clip: 0.2
  value_clip: 0.2
  clip_predicted_values: true
  entropy_loss_scale: 0.0
  value_loss_scale: 2.0
  kl_threshold: 0.0
  rewards_shaper_scale: 1.0
  time_limit_bootstrap: false
  experiment:
    directory: C:\Users\ojfer\Documents\Projects\Robotics\Theatrum\logs\skrl\basis_dir
    experiment_name: 2025-04-13_23-45-51_ppo_torch
    write_interval: 50
    checkpoint_interval: 1000
trainer:
  class: SequentialTrainer
  timesteps: 64000
  environment_info: log
  close_environment_at_exit: false
